services:
  - type: web
    name: restaurant-web-app
    env: node
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    envVars:
      - key: NODE_VERSION
        value: 18.x.0
    healthCheckPath: /

